export const scholarships = [
  {
    id: 1,
    name: 'National Merit Scholarship',
    provider: 'Government of India',
    amount: '₹12,000/year',
    deadline: 'Urgent',
    deadlineDate: 'Mar 15, 2025',
    minGPA: 8.0,
    needBased: false,
    categories: ['All'],
    fields: ['All'],
    genderEligible: ['All'],
    link: 'https://scholarships.gov.in',
    description: 'Awarded to top academic performers across all streams in India.',
    tags: ['Merit', 'All Categories'],
  },
  {
    id: 2,
    name: 'Post-Matric SC/ST Scholarship',
    provider: 'Ministry of Social Justice',
    amount: '₹18,000/year',
    deadline: 'Soon',
    deadlineDate: 'Apr 10, 2025',
    minGPA: 5.0,
    needBased: true,
    categories: ['SC', 'ST'],
    fields: ['All'],
    genderEligible: ['All'],
    link: 'https://scholarships.gov.in',
    description: 'Supports SC/ST students with full tuition and maintenance allowance.',
    tags: ['Need-Based', 'SC/ST'],
  },
  {
    id: 3,
    name: 'Tata Scholarship for STEM',
    provider: 'Tata Trust',
    amount: '₹50,000/year',
    deadline: 'Later',
    deadlineDate: 'Jun 20, 2025',
    minGPA: 7.5,
    needBased: true,
    categories: ['All'],
    fields: ['Computer Science', 'Engineering', 'Medicine', 'Architecture'],
    genderEligible: ['All'],
    link: 'https://tatatrusts.org',
    description: 'Encouraging STEM students from low-income families to excel.',
    tags: ['STEM', 'Need-Based'],
  },
  {
    id: 4,
    name: 'Vidyasaarathi OBC Scholarship',
    provider: 'NSDL Foundation',
    amount: '₹25,000/year',
    deadline: 'Urgent',
    deadlineDate: 'Mar 5, 2025',
    minGPA: 6.0,
    needBased: true,
    categories: ['OBC'],
    fields: ['All'],
    genderEligible: ['All'],
    link: 'https://www.vidyasaarathi.co.in',
    description: 'Targeted financial support for OBC students with economic need.',
    tags: ['OBC', 'Need-Based'],
  },
  {
    id: 5,
    name: 'Aditya Birla Scholarships',
    provider: 'Aditya Birla Group',
    amount: '₹65,000/year',
    deadline: 'Soon',
    deadlineDate: 'Apr 30, 2025',
    minGPA: 9.0,
    needBased: false,
    categories: ['All'],
    fields: ['Business', 'Engineering', 'Law'],
    genderEligible: ['All'],
    link: 'https://adityabirla.com/scholarships',
    description: 'Prestigious merit scholarship for top-performing students in professional courses.',
    tags: ['Merit', 'Prestigious'],
  },
  {
    id: 6,
    name: 'Central Sector Scheme',
    provider: 'Ministry of Education',
    amount: '₹12,000/year',
    deadline: 'Later',
    deadlineDate: 'Jul 1, 2025',
    minGPA: 7.0,
    needBased: true,
    categories: ['All'],
    fields: ['All'],
    genderEligible: ['All'],
    link: 'https://scholarships.gov.in',
    description: 'For students from families below income threshold across any stream.',
    tags: ['Need-Based', 'All Streams'],
  },
  {
    id: 7,
    name: 'Inspire Scholarship DST',
    provider: 'Dept. of Science & Technology',
    amount: '₹80,000/year',
    deadline: 'Urgent',
    deadlineDate: 'Mar 20, 2025',
    minGPA: 8.5,
    needBased: false,
    categories: ['All'],
    fields: ['Computer Science', 'Engineering', 'Agriculture', 'Medicine'],
    genderEligible: ['All'],
    link: 'https://online-inspire.gov.in',
    description: 'For top 1% students pursuing natural sciences and technology programs.',
    tags: ['Merit', 'STEM', 'Prestigious'],
  },
  {
    id: 8,
    name: 'Pragati Scholarship for Girls',
    provider: 'AICTE',
    amount: '₹30,000/year',
    deadline: 'Soon',
    deadlineDate: 'May 15, 2025',
    minGPA: 6.5,
    needBased: true,
    categories: ['All'],
    fields: ['Engineering', 'Computer Science', 'Architecture'],
    genderEligible: ['Female'],
    link: 'https://aicte-pragati-saksham-gov.in',
    description: 'Supporting female students in technical education exclusively.',
    tags: ['Women Only', 'Technical'],
  },
  {
    id: 9,
    name: 'EWS Merit Scholarship',
    provider: 'Ministry of Education',
    amount: '₹20,000/year',
    deadline: 'Later',
    deadlineDate: 'Jun 1, 2025',
    minGPA: 7.5,
    needBased: true,
    categories: ['EWS', 'General'],
    fields: ['All'],
    genderEligible: ['All'],
    link: 'https://scholarships.gov.in',
    description: 'For EWS and General category students facing financial constraints.',
    tags: ['EWS', 'Need-Based'],
  },
  {
    id: 10,
    name: 'Begum Hazrat Mahal Scholarship',
    provider: 'Maulana Azad Foundation',
    amount: '₹10,000/year',
    deadline: 'Urgent',
    deadlineDate: 'Mar 25, 2025',
    minGPA: 5.5,
    needBased: true,
    categories: ['All'],
    fields: ['All'],
    genderEligible: ['Female'],
    link: 'https://maef.net.in',
    description: 'Supporting minority community girls in higher education programs.',
    tags: ['Women Only', 'Minority'],
  },
];
